version: '3'
services:
      adminmongo:
          image: adminmongo
          container_name: adminmongo
          user: root
          environment:
            - HOST=0.0.0.0
            - PORT=1234
          ports:
            - "1234:1234"
          restart: always
