version: '3'
services:
      adminmongo:
          image: chalut/adminmongo:1.0.0
          container_name: adminmongo
          user: root
          environment:
            - HOST=0.0.0.0
            - PORT=1234
          ports:
            - "1234:1234"
          restart: always
