name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
         name: Checkout
         uses: actions/checkout@v2
      - 
         name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: "chalut"
           password: "Chalut002."
      -
         name: docker build
         run: docker build . --file Dockerfile --tag chalut/adminmongo:1.0.0
      -
         name: Docker push
         run: docker push chalut/adminmongo:1.0.0
      -   
         name: 'Noti JOM'
         uses: snow-actions/line-notify@v1.0.0
         with:
             access_token: OoeNUGioVM5rzvnDQvXOpOIqqVD2vUkpxRyGeeRIZAF
             message: omnidb-server:3.0.3b PUSH to dockerhub complete.
